name: Create Tag

on:
  push:
    branches:
      # explicit deny all here to make sure there isnt a commit loop
      - '!*'
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: check if tag already exists
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* && git rev-parse "$(cat VERSION)" >/dev/null 2>&1 && exit 1 || exit 0

      - name: create tag
        run: git config --global user.email "${{ github.actor }}" && git config --global user.name "${{ github.actor }}" && git tag -a -m "$(cat VERSION)" $(cat VERSION) && git push --follow-tags
